---
name: easy-ecr - verify and build

on:
  push:
    branches:
      - main
    paths:
      - 'easy-ecr/**'
  pull_request:
    branches:
      - main
    paths:
      - 'easy-ecr/**'

jobs:
  test-and-verify:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: 'v0.60.0'
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Run verification
        run: |
          make codeartifact-repo-verify
  release:
    needs: test-and-verify
    uses: ./.github/workflows/common-release.yaml
    with:
      tag-prefix: 'easy-ecr-'
